# Generated by Django 4.1.4 on 2022-12-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tvn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('hour', models.CharField(blank=True, max_length=5)),
                ('link', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tvp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('hour', models.CharField(blank=True, max_length=5)),
                ('link', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
