# Generated by Django 4.1.4 on 2022-12-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tvn_tvp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvn',
            name='hour',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='tvn',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tvp',
            name='hour',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='tvp',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
